### PR TITLE
Dev/55 staff app form

### PR DESCRIPTION
**Pull request by sdmungov**

### CODE REVIEW

**Comment by FB-Reda** [comment]
> Maybe consider a cropped version of this photo for the hero?
> DSC_0088
> 
Edited to add cropped version:
Cropped Staff

**Review by he-james — APPROVED** [review]

**Review by FB-Reda — CHANGES_REQUESTED** [review]
Just needs the picture change before deployment.

**Comment by he-james** [comment]
> Just needs the picture change before deployment.

@FB-Reda @sdmungov did this - check the jumbotron component, had to add a new prop so let me know if it's out of line

**Comment by FB-Reda** [comment]
@he-james Ahh the deployment to preview failed so I missed it

**Comment by he-james** [comment]
> @he-james Ahh the deployment to preview failed so I missed it

Did not make the new prop optional so had a compilation error - fixed

**Review by FB-Reda — APPROVED** [review]

**Review by he-james — APPROVED** [review]

**Pull request merged**
